"""Assemble reports/results.md from saved run outputs. It computes nothing new about the models.

    python -m scripts.make_report
    python -m scripts.make_report --llm-sample     # use the *_s runs (LLM-sample study)

Every number comes from reports/runs/*/metrics.json, the cost files, and predictions.parquet.
An experiment that has not been run appears as "not run", never as an estimate.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from src.config import load_config
from src.features.assemble import llm_features_path
from src.features.llm_extract import FIELDS, LLMSettings

EXPERIMENTS = ["e0", "e1", "e2", "e3", "e4"]
WHY_NOT_RUN = {
    "e2": "LLM features not extracted yet (pending Kaggle vLLM run); see Limitations",
    "e3": "needs the E2 LLM features",
}


def _load(path: Path) -> dict[str, Any] | None:
    return json.loads(path.read_text(encoding="utf-8")) if path.exists() else None


def _ci(r: dict | None, fmt: str = ".4f") -> str:
    if not r:
        return "–"
    return f"{r['value']:{fmt}} [{r['ci_low']:{fmt}}, {r['ci_high']:{fmt}}]"


def _diff(r: dict | None) -> str:
    if not r:
        return "–"
    return f"{r['diff']:+.4f} [{r['ci_low']:+.4f}, {r['ci_high']:+.4f}]"


def _md_table(df: pd.DataFrame) -> str:
    cols = list(df.columns)
    out = ["| " + " | ".join(cols) + " |", "|" + "|".join("---" for _ in cols) + "|"]
    out += ["| " + " | ".join(str(v) for v in row) + " |" for row in df.itertuples(index=False)]
    return "\n".join(out)


def _logit(p: np.ndarray) -> np.ndarray:
    p = np.clip(p, 1e-6, 1 - 1e-6)
    return np.log(p / (1 - p))


def disagreement_cases(
    runs: Path, new: str, base: str, df: pd.DataFrame, k: int, llm: pd.DataFrame | None
) -> pd.DataFrame:
    """Test loans where `new` and `base` disagree most, by absolute log-odds difference."""
    a = pd.read_parquet(runs / new / "predictions.parquet")
    b = pd.read_parquet(runs / base / "predictions.parquet")
    m = a[a["split"] == "test"].merge(b[["id", "score"]], on="id", suffixes=("", "_base"))
    m["dlogit"] = _logit(m["score"].to_numpy()) - _logit(m["score_base"].to_numpy())
    top = m.reindex(m["dlogit"].abs().sort_values(ascending=False).index).head(k)
    top = top.merge(df[["id", "desc", "grade", "int_rate", "purpose"]], on="id", how="left")
    if llm is not None:
        top = top.merge(llm, on="id", how="left")
    return top


def _case_block(r: pd.Series, new: str, base: str, has_llm: bool) -> str:
    outcome = "**defaulted**" if r["target"] == 1 else "repaid"
    text = r["desc"] if len(r["desc"]) <= 700 else r["desc"][:700] + " …"
    text = text.replace("|", "\\|")
    moved = "raised" if r["dlogit"] > 0 else "lowered"
    right = (r["dlogit"] > 0) == (r["target"] == 1)
    lines = [
        f"**id {r['id']}** · {r['issue_d']:%Y-%m} · grade {r['grade']} · rate {r['int_rate']:.2f}% "
        f"· purpose `{r['purpose']}` · outcome: {outcome}",
        f"- PD {base.upper()} {r['score_base']:.3f} → {new.upper()} {r['score']:.3f} "
        f"({moved}; {'toward' if right else 'away from'} the actual outcome)",
        f"- desc: “{text}”",
    ]
    if has_llm:
        js = {f: (None if pd.isna(r.get(f)) else r.get(f)) for f in FIELDS}
        js = {k: (v.item() if hasattr(v, "item") else v) for k, v in js.items()}
        js = {k: (int(v) if isinstance(v, float) and v.is_integer() else v) for k, v in js.items()}
        lines.append(f"- LLM: `{json.dumps(js)}`")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawTextHelpFormatter)
    ap.add_argument("--config", default="configs/base.yaml")
    ap.add_argument("--llm-sample", action="store_true")
    ap.add_argument("--n-cases", type=int, default=20)
    args = ap.parse_args()

    cfg = load_config(args.config)
    reports = Path(cfg["paths"]["reports_dir"])
    runs = reports / "runs"
    sfx = "_s" if args.llm_sample else ""
    M = {e: _load(runs / f"{e}{sfx}" / "metrics.json") for e in EXPERIMENTS}
    if not M["e0"]:
        raise SystemExit("E0 has not been run; nothing to report.")
    data = _load(reports / "data" / "prepare_data.json") or {}
    processed = Path(cfg["paths"]["processed"])
    df = pd.read_parquet(processed, columns=["id", "desc", "grade", "int_rate", "purpose"])
    llm_model = cfg["llm"]["model"]
    llm_path = llm_features_path(processed.parent, llm_model)
    llm_df = pd.read_parquet(llm_path) if llm_path.exists() else None

    out: list[str] = []
    w = out.append
    e0 = M["e0"]
    w("# Results: do LLM-derived text features improve a PD model?\n")
    w(
        f"_Generated by `python -m scripts.make_report{' --llm-sample' if sfx else ''}` from "
        "`reports/runs/*/metrics.json`. Do not edit by hand._\n"
    )

    # ---------------- summary ----------------
    w("## Summary\n")
    bullets = []
    if M["e1"]:
        g = M["e1"][f"vs_e0{sfx}"]["gini_diff"]
        sig = "significant" if g["ci_low"] > 0 else "not significant at 95%"
        bullets.append(
            f"**Embeddings (E1)** change test Gini by {_diff(g)} vs the tabular "
            f"baseline, one-sided p = {g['p_value_one_sided']:.3f} ({sig})."
        )
    if M["e2"]:
        g = M["e2"][f"vs_e0{sfx}"]["gini_diff"]
        sig = "significant" if g["ci_low"] > 0 else "not significant at 95%"
        bullets.append(
            f"**LLM features (E2)** change test Gini by {_diff(g)}, one-sided "
            f"p = {g['p_value_one_sided']:.3f} ({sig})."
        )
        if M["e3"]:
            g3 = M["e3"][f"vs_e0{sfx}"]["gini_diff"]
            g1 = M["e1"][f"vs_e0{sfx}"]["gini_diff"]["diff"] if M["e1"] else None
            tail = (
                f" That is no better than embeddings alone ({g1:+.4f}): the two text "
                "representations do not add up."
                if g1 is not None and g3["diff"] <= g1
                else ""
            )
            bullets.append(
                f"**Both together (E3)** change test Gini by {_diff(g3)}, one-sided "
                f"p = {g3['p_value_one_sided']:.3f}.{tail}"
            )
    else:
        bullets.append(
            "**LLM features (E2, E3): not run yet**, because no funded LLM endpoint "
            "was available. RQ2 is still open; see Limitations."
        )
    if M["e4"]:
        bullets.append(
            f"**Text alone (E4, TF-IDF + LR)** reaches test Gini "
            f"{_ci(M['e4']['gini']['test'])}. The descriptions carry real default "
            f"signal, but most of it overlaps with the tabular features."
        )
    bullets.append(
        f"Baseline **E0** test Gini {_ci(e0['gini']['test'])}, well calibrated "
        f"(mean PD {e0['mean_pd_test']:.3f} vs observed "
        f"{e0['default_rate']['test']:.3f}), score PSI train→test "
        f"{e0['psi_score']['train_vs_test']:.4f}."
    )
    w("\n".join(f"- {b}" for b in bullets) + "\n")

    # ---------------- data ----------------
    w("## Data and protocol\n")
    if data:
        funnel = " → ".join(f"{f['rows']:,} ({f['step']})" for f in data["funnel"])
        w(f"- Lending Club accepted loans 2007–2018. Row funnel: {funnel}.")
    sp = pd.DataFrame(data.get("splits", []))
    if not sp.empty:
        sp = sp.assign(
            share=sp["share"].map("{:.1%}".format),
            default_rate=sp["default_rate"].map("{:.2%}".format),
        )
        w("- Out-of-time split by issue month (no month shared between splits):\n")
        w(_md_table(sp[["split", "rows", "first_month", "last_month", "share", "default_rate"]]))
    w(
        "\n- All CatBoost experiments use identical settings, seed "
        f"{e0['seed']}, early stopping on validation AUC. Test is only used for the numbers "
        "below. CIs: percentile bootstrap over test loans, "
        f"{cfg['eval']['n_bootstrap']} resamples. Differences vs E0 use a **paired** bootstrap "
        "(same resampled loans for both models).\n"
    )

    # ---------------- results table ----------------
    w("## Results (test set)\n")
    rows = []
    for e in EXPERIMENTS:
        m = M[e]
        if not m:
            rows.append([e.upper(), "–", "–", "not run", "–", "–", "–", WHY_NOT_RUN.get(e, "")])
            continue
        vs = m.get(f"vs_e0{sfx}")
        n_feat = m.get("n_features", "TF-IDF" if m.get("model") == "tfidf_logreg" else "–")
        rows.append(
            [
                e.upper(),
                m.get("description", ""),
                n_feat,
                _ci(m["gini"]["test"]),
                _ci(m["auc_test"]),
                _ci(m["brier_test"]),
                _diff(vs["gini_diff"]) if vs else "(baseline)",
                f"{vs['gini_diff']['p_value_one_sided']:.3f}" if vs else "",
            ]
        )
    w(
        _md_table(
            pd.DataFrame(
                rows,
                columns=[
                    "exp",
                    "features",
                    "# feat",
                    "Gini [95% CI]",
                    "AUC [95% CI]",
                    "Brier [95% CI]",
                    "ΔGini vs E0 [95% CI, paired]",
                    "p (Δ≤0)",
                ],
            )
        )
    )
    w("")

    # ---------------- stability ----------------
    w("\n## Stability over time\n")
    qrows = []
    for e in EXPERIMENTS:
        if not M[e]:
            continue
        for q in M[e]["gini_by_quarter_test"]:
            if q.get("gini") is not None and not pd.isna(q.get("gini")):
                qrows.append(
                    [
                        e.upper(),
                        q["period"],
                        f"{q['n']:,}",
                        f"{q['gini']:.4f} [{q['ci_low']:.4f}, {q['ci_high']:.4f}]",
                    ]
                )
    w(_md_table(pd.DataFrame(qrows, columns=["exp", "issue quarter", "n", "Gini [95% CI]"])))
    w(
        "\nOnly two test quarters have enough loans (≥ "
        f"{cfg['eval']['min_period_n']}), because `desc` disappears after March 2014, so "
        "stability evidence is thin (see Limitations).\n"
    )
    prow = [
        [
            e.upper(),
            f"{M[e]['psi_score']['train_vs_val']:.4f}",
            f"{M[e]['psi_score']['train_vs_test']:.4f}",
            f"{M[e]['brier_skill_test']:.4f}",
            f"{M[e]['mean_pd_test']:.4f} / {M[e]['default_rate']['test']:.4f}",
        ]
        for e in EXPERIMENTS
        if M[e]
    ]
    w(
        _md_table(
            pd.DataFrame(
                prow,
                columns=[
                    "exp",
                    "PSI train→val",
                    "PSI train→test",
                    "Brier skill",
                    "mean PD / observed (test)",
                ],
            )
        )
    )
    w(
        "\nPSI < 0.10 counts as stable. Train scores are in-sample, which slightly overstates "
        "their spread.\n"
    )
    figs = [
        f"![{e.upper()} calibration](figures/{e}{sfx}_calibration.png)" for e in EXPERIMENTS if M[e]
    ]
    w("Calibration (reliability) by score decile:\n\n" + " ".join(figs) + "\n")

    # ---------------- interpretability ----------------
    w("## Interpretability\n")
    w("### SHAP for LLM features\n")
    shap_runs = [e for e in ("e2", "e3") if M[e] and "shap_llm" in M[e]]
    if not shap_runs:
        w(
            "_Not available: E2/E3 have not been run._ When they are, this section shows "
            "the share of total |SHAP| carried by the eight LLM features, their rank among all "
            "features, and the mean SHAP (log-odds) per value, e.g. how much "
            "`financial_stress = 3` moves PD. The code for this is done and tested.\n"
        )
    for e in shap_runs:
        s = M[e]["shap_llm"]
        w(
            f"**{e.upper()}**: LLM features carry {s['llm_share_of_total_abs_shap']:.1%} of total "
            f"mean |SHAP| on {s['n_rows']:,} test loans.\n"
        )
        t = pd.DataFrame(
            {
                "feature": list(s["ranks"]),
                "rank": list(s["ranks"].values()),
                "mean |SHAP|": [f"{v:.4f}" for v in s["mean_abs_shap"].values()],
            }
        )
        w(_md_table(t.sort_values("rank")) + "\n")
        w(f"![{e.upper()} SHAP by value](figures/{e}{sfx}_shap_llm.png)\n")
    if shap_runs and llm_df is not None:
        w("### What the extracted values look like\n")
        full = pd.read_parquet(processed, columns=["id", "desc", "target"]).merge(llm_df, on="id")
        full["chars"] = full["desc"].str.len()
        trow = []
        for f in FIELDS:
            for val, g in full.groupby(f, observed=True):
                val = int(val) if isinstance(val, float) else val
                share, dr = len(g) / len(full), g["target"].mean()
                chars = g["chars"].median()
                trow.append([f, val, f"{len(g):,}", f"{share:.1%}", f"{dr:.1%}", f"{chars:.0f}"])
        cols = ["feature", "value", "loans", "share", "default rate", "median desc chars"]
        w(_md_table(pd.DataFrame(trow, columns=cols)) + "\n")
        w(
            "All splits pooled, so this table is descriptive and plays no part in model "
            "selection. Two things stand out. `text_quality` rises with description length, so "
            "its high SHAP rank may reflect how much the borrower wrote as much as how well. "
            "`mentions_other_debts` is true for most loans and its two groups default at the "
            "same rate, so it carries almost no information.\n"
        )
    if M["e4"]:
        w("### What the words say (E4 TF-IDF coefficients)\n")
        w("- Raise PD: " + ", ".join(f"`{t}`" for t in M["e4"]["top_default_terms"]))
        w("- Lower PD: " + ", ".join(f"`{t}`" for t in M["e4"]["top_repay_terms"]) + "\n")
        w(
            "Borrowers who *need help with bills* or fund a *business* default more. Those who "
            "*refinance* card balances at a lower *interest rate* default less. "
            "This is consistent with the `purpose` field, and may explain why E1 adds little "
            "on top of the tabular features.\n"
        )

    # ---------------- cost ----------------
    w("## Cost per application\n")
    crow = []
    emb = _load(runs / f"embed_{cfg['embeddings']['model_name'].split('/')[-1]}" / "cost.json")
    if emb:
        crow.append(
            [
                "E1 embeddings",
                emb["model_name"],
                f"{emb['device']} ({emb['precision']})",
                f"{emb['mean_tokens']:.0f}",
                f"{1000 / emb['texts_per_second']:.1f} ms",
                "$0 (local)",
                f"{emb['n_computed']:,} texts in {emb['seconds'] / 60:.0f} min",
            ]
        )
    llm_cost = _load(runs / f"llm_{LLMSettings(model=llm_model).slug}" / "cost.json")
    if llm_cost and llm_cost.get("n_fresh_calls"):
        usd = llm_cost.get("usd_per_application")
        crow.append(
            [
                "E2 LLM extraction",
                llm_model,
                f"{llm_cost.get('hardware') or 'API'}, concurrency {llm_cost['concurrency']}",
                f"{llm_cost['mean_prompt_tokens']:.0f} in / "
                f"{llm_cost['mean_completion_tokens']:.0f} out",
                f"{llm_cost['latency_p50_s']:.2f} s p50 / {llm_cost['latency_p95_s']:.2f} s p95",
                f"${usd:.6f}"
                if usd is not None
                else f"{llm_cost['accelerator_seconds_per_application']:.3f} GPU-s"
                if llm_cost.get("accelerator_seconds_per_application")
                else "not measured",
                f"valid {llm_cost['valid_rate']:.2%}, retry {llm_cost['retry_rate']:.2%}",
            ]
        )
    else:
        crow.append(
            [
                "E2 LLM extraction",
                llm_model,
                "–",
                "~520 in / ~100 out (20-text pilot)",
                "not measured",
                "not measured",
                "not run (planned: vLLM on a Kaggle T4)",
            ]
        )
    if M["e4"]:
        crow.append(
            [
                "E4 TF-IDF + LR",
                "sklearn",
                "cpu",
                "–",
                "not measured",
                "$0",
                f"fit {M['e4']['fit_seconds']:.0f} s incl. C search",
            ]
        )
    crow.append(
        [
            "CatBoost scoring (all exps)",
            "catboost",
            "cpu",
            "–",
            "not measured",
            "$0",
            f"E0 fit {e0['fit_seconds']:.0f} s",
        ]
    )
    w(
        _md_table(
            pd.DataFrame(
                crow,
                columns=[
                    "step",
                    "model",
                    "hardware",
                    "tokens / app",
                    "latency / app",
                    "$ / app",
                    "notes",
                ],
            )
        )
    )
    w(
        "\nEmbedding latency is batch throughput (1 / texts per second) on a laptop CPU with 4 "
        "threads (fp32). GPU throughput for embeddings has not been measured here.\n"
    )
    if llm_cost and llm_cost.get("accelerator_seconds_per_application"):
        w(
            f"LLM timing comes from {llm_cost['n_fresh_calls']:,} fresh calls on "
            f"{llm_cost.get('n_shards', 1)} GPU (one of the two GPUs in the final Kaggle run; "
            "the other GPU and the earlier, interrupted runs left no timing record, only cached "
            "answers). GPU-seconds per application is wall time divided by calls, which is the "
            "cost that matters for a batch job. The per-request latency is high because "
            f"{llm_cost['concurrency']} requests were in flight at once: it measures queueing in "
            "a throughput-tuned server, not what a single online request would take. No dollar "
            "price is given: the GPU was a free Kaggle T4.\n"
        )

    # ---------------- error analysis ----------------
    w(f"## Error analysis: {args.n_cases} test loans with the largest disagreement\n")
    if M["e2"]:
        new, has_llm = "e2", True
    elif M["e1"]:
        new, has_llm = "e1", False
        w(
            "> E2 has not been run, so this section compares **E1 vs E0** in the meantime. "
            "It shows which descriptions move PD when embeddings are added. Once E2 is run, "
            "`make_report` switches to E2 vs E0 and shows each loan's LLM JSON.\n"
        )
    else:
        new = None
    if new:
        cases = disagreement_cases(
            runs,
            new + sfx,
            "e0" + sfx,
            df,
            args.n_cases,
            llm_df[["id", *FIELDS]] if (has_llm and llm_df is not None) else None,
        )
        right = ((cases["dlogit"] > 0) == (cases["target"] == 1)).mean()
        w(
            f"Ranked by |log-odds({new.upper()}) − log-odds(E0)|. In {right:.0%} of these cases "
            f"{new.upper()} moved PD toward the actual outcome. With a ~16% default rate, "
            'extreme moves are expected to be "wrong" often, so this is descriptive, '
            "not a test.\n"
        )
        for _, r in cases.iterrows():
            w(_case_block(r, new, "e0", has_llm) + "\n")

    # ---------------- limitations ----------------
    w("## Limitations\n")
    steps = {f["step"]: f["rows"] for f in data.get("funnel", [])}
    n_text = next((v for k, v in steps.items() if k.startswith("unique")), 0)
    n_finished = next((v for k, v in steps.items() if k.startswith("finished")), 0)
    if M["e2"] and llm_df is not None:
        n_null = int(llm_df[FIELDS[0]].isna().sum())
        llm_limitation = (
            "**One small LLM, one prompt, labels not audited at scale.** The features come from "
            f"{llm_model} (4-bit AWQ) with a single prompt written before seeing any results. "
            f"{n_null} of {len(llm_df):,} answers failed schema validation twice and are null "
            "(the model invented a purpose category such as `travel`). Valid JSON is not the "
            "same as a correct label: in a hand review of the 20-text pilot "
            "(reports/pilot/) at least 4 outputs had a clearly wrong field, and no larger audit "
            "was done. So E2 measures what these noisy labels add, not what the text could add "
            "with a stronger model, a tuned prompt or human labels."
        )
    else:
        llm_limitation = (
            "**LLM features pending.** E2/E3 (RQ2) have not been run. Extraction runs on "
            "Qwen2.5-7B-AWQ on a Kaggle T4 (notebooks/kaggle_e2_llm_extract.ipynb)."
        )
    lim = [
        "**Text only exists up to March 2014.** Lending Club removed the description field, so "
        f"the study covers 2007–2014 loans ({n_text:,} of {n_finished:,} finished loans) and the "
        "out-of-time test window is only 4 issue months (Dec 2013 – Mar 2014). Gini by "
        "quarter rests on 2 quarters, so claims about stability over time are weak.",
        "**Selection effect of the text filter.** Borrowers who wrote a description, and "
        "vintages where it was common, are not a random subset of the portfolio. Results do "
        "not carry over to applicants without free text.",
        "**Lending Club's own model is a feature.** `int_rate`, `grade` and `sub_grade` "
        "already contain LC's risk assessment, and LC's underwriters saw the same text. "
        "Text features are measured against a very strong baseline, so a small ΔGini is "
        "expected.",
        "**Accepted loans only.** There is no reject inference: the model is trained and "
        "tested on loans that LC approved.",
        "**Uncertainty covers test sampling, not training randomness.** Each experiment is "
        "one CatBoost fit with one seed, and small ΔGini values (a few thousandths) are "
        "comparable to typical seed variance. A multi-seed run is the next step before "
        "claiming an effect.",
        "**Untuned text reduction.** The embedding reduction (32 PCA components) is fixed a "
        "priori. Choosing it on validation is legitimate, but choosing it on test would "
        "inflate the gain.",
        "**Outcome windows overlap.** Train loans can default after test loans are issued. "
        "Features are all known at origination, so this is not feature leakage, but train "
        "labels reflect some macro conditions from the test period.",
        llm_limitation,
        "**Leakage control is list-based.** An explicit allowlist and denylist of 151 columns "
        "is enforced by tests, but it relies on LC's data dictionary being accurate about "
        "which fields are known at application time.",
        "**Fair lending.** `zip_code` is excluded as a redlining proxy, but `addr_state` and "
        "free text can still encode protected characteristics (e.g. mentions of family or "
        "health). A production use would need a disparate-impact review.",
    ]
    w("\n".join(f"{i}. {t}" for i, t in enumerate(lim, 1)) + "\n")

    w("## Reproduce\n")
    w(
        "```bash\npython -m scripts.prepare_data\npython -m scripts.run_experiment --config "
        "configs/e0.yaml\npython -m scripts.embed --config configs/e1.yaml\n"
        "python -m scripts.run_experiment --config configs/e1.yaml\n"
        "python -m scripts.llm_extract --config configs/e2.yaml      # or the Kaggle notebook\n"
        "python -m scripts.run_experiment --config configs/e2.yaml\n"
        "python -m scripts.run_experiment --config configs/e3.yaml\n"
        "python -m scripts.run_experiment --config configs/e4.yaml\n"
        "python -m scripts.make_report\n```\n"
    )

    path = reports / ("results_llm_sample.md" if sfx else "results.md")
    path.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {path} ({sum(1 for e in M.values() if e)} of {len(EXPERIMENTS)} experiments)")


if __name__ == "__main__":
    main()
